export default [
    {
        name: "textInput",
        value: "",
        type: "text",
        label: "Name",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        placeholder: "i.e. Users DB (readonly) or Internal Admin API",
        required: true,
        disabled: false,
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        name: "emailInput",
        value: "",
        type: "email",
        label: "Email Address",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        placeholder: "i.e. Users DB (readonly) or Internal Admin API",
        required: true,
        disabled: false,
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        name: "numberInput",
        value: "",
        type: "number",
        label: "Number",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        placeholder: "i.e. Users DB (readonly) or Internal Admin API",
        required: true,
        disabled: false,
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        name: "passwordInput",
        value: "",
        type: "password",
        label: "Password",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        placeholder: "i.e. Users DB (readonly) or Internal Admin API",
        required: true,
        disabled: false,
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        name: "urlInput",
        value: "",
        type: "url",
        label: "Url",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        placeholder: "i.e. Users DB (readonly) or Internal Admin API",
        required: true,
        disabled: false,
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        name: "textareaInput",
        value: "",
        type: "textarea",
        label: "Textarea",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        placeholder: "i.e. Users DB (readonly) or Internal Admin API",
        required: true,
        disabled: false,
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        name: "fileInput",
        value: "",
        type: "file",
        label: "File",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        placeholder: "File",
        required: true,
        disabled: false,
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        name: "radioInput",
        value: "",
        type: "radio",
        label: "Radio",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        required: true,
        disabled: false,
        checked: false,
        options: [
            {
                label: "Radio 1",
                subLabel: "",
                value: "radio1",
            },
            {
                label: "Radio 2",
                subLabel: "",
                value: "radio2",
            },
            {
                label: "Radio 3",
                subLabel: "",
                value: "radio3",
            },
        ],
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        name: "checkboxInput",
        value: "",
        type: "checkbox",
        label: "Checkbox",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        required: false,
        disabled: false,
        checked: false,
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        name: "selectInput",
        value: "",
        type: "select",
        label: "Select",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        required: true,
        disabled: false,
        options: [
            {
                label: "Select Option 1",
                value: "selectOption1",
            },
            {
                label: "Select Option 2",
                value: "selectOption2",
            },
            {
                label: "Select Option 3",
                value: "selectOption3",
            },
        ],
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        name: "listInputWith1Option",
        value: "",
        type: "list",
        label: "List with 1 Option",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        required: true,
        disabled: false,
        options: [
            {
                name: "file",
                value: "",
                type: "file",
                label: "File",
                subLabel: "",
                placeholder: "File",
                required: true,
                disabled: false,
                validation: {},
                tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
            },
        ],
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        name: "listInputWith2Option",
        value: "",
        type: "list",
        label: "List with 2 Options",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        required: true,
        disabled: false,
        options: [
            {
                name: "username",
                value: "",
                type: "text",
                label: "Username",
                subLabel: "",
                placeholder: "UserName",
                required: true,
                disabled: false,
                validation: {},
                tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
            },
            {
                name: "password",
                value: "",
                type: "password",
                label: "Password",
                subLabel: "",
                placeholder: "Password",
                required: true,
                disabled: false,
                validation: {},
                tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
            },
        ],
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
    },
    {
        type: "html",
        content:
            "<div class='space-y-2 text-balance rounded-md bg-slate-100 p-3 text-xs'>   <p class='font-medium'>SSH public key authentication</p>   <p class='text-slate-500'> Download public key here and add it to your ~/.ssh/authorized_keys You'll need to create a user named retool. Click here for docs on how to use this feature.</p> </div>",
    },
    {
        name: "tabs",
        value: "",
        type: "tabs",
        label: "Tabs",
        subLabel: "",
        required: true,
        disabled: false,
        checked: false,
        options: [
            {
                label: "Tab 1",
                subLabel: "",
                value: "tab1",
            },
            {
                label: "Tab 2",
                subLabel: "",
                value: "tab2",
            },
        ],
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        isConditional: true,
        conditions: {
            tab1: [
                {
                    name: "textInput",
                    value: "",
                    type: "text",
                    label: "Name",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
            ],
            tab2: [
                {
                    name: "fileInput",
                    value: "",
                    type: "file",
                    label: "File",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "File",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
            ],
        },
    },
    {
        name: "radioInputConditional",
        value: "",
        type: "radio",
        label: "Radio",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        required: true,
        disabled: false,
        checked: false,
        options: [
            {
                label: "Radio 1",
                subLabel: "",
                value: "radio1",
            },
            {
                label: "Radio 2",
                subLabel: "",
                value: "radio2",
            },
            {
                label: "Radio 3",
                subLabel: "",
                value: "radio3",
            },
        ],
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        isConditional: true,
        conditions: {
            radio1: [
                {
                    name: "textInput",
                    value: "",
                    type: "text",
                    label: "Name",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "emailInput",
                    value: "",
                    type: "email",
                    label: "Email Address",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "numberInput",
                    value: "",
                    type: "number",
                    label: "Number",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "passwordInput",
                    value: "",
                    type: "password",
                    label: "Password",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "urlInput",
                    value: "",
                    type: "url",
                    label: "Url",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "textareaInput",
                    value: "",
                    type: "textarea",
                    label: "Textarea",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "fileInput",
                    value: "",
                    type: "file",
                    label: "File",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "File",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "radioInputChildConditional",
                    value: "",
                    type: "radio",
                    label: "Radio",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    checked: false,
                    options: [
                        {
                            label: "Radio 1",
                            subLabel: "",
                            value: "radio1",
                        },
                        {
                            label: "Radio 2",
                            subLabel: "",
                            value: "radio2",
                        },
                        {
                            label: "Radio 3",
                            subLabel: "",
                            value: "radio3",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "checkboxInput",
                    value: "",
                    type: "checkbox",
                    label: "Checkbox",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: false,
                    disabled: false,
                    checked: false,
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "selectInput",
                    value: "",
                    type: "select",
                    label: "Select",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    options: [
                        {
                            label: "Select Option 1",
                            value: "selectOption1",
                        },
                        {
                            label: "Select Option 2",
                            value: "selectOption2",
                        },
                        {
                            label: "Select Option 3",
                            value: "selectOption3",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "listInputWith1Option",
                    value: "",
                    type: "list",
                    label: "List with 1 Option",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    options: [
                        {
                            name: "file",
                            value: "",
                            type: "file",
                            label: "File",
                            subLabel: "",
                            placeholder: "File",
                            required: true,
                            disabled: false,
                            validation: {},
                            tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "listInputWith2Option",
                    value: "",
                    type: "list",
                    label: "List with 2 Options",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    options: [
                        {
                            name: "username",
                            value: "",
                            type: "text",
                            label: "Username",
                            subLabel: "",
                            placeholder: "UserName",
                            required: true,
                            disabled: false,
                            validation: {},
                            tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                        },
                        {
                            name: "password",
                            value: "",
                            type: "password",
                            label: "Password",
                            subLabel: "",
                            placeholder: "Password",
                            required: true,
                            disabled: false,
                            validation: {},
                            tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    type: "html",
                    content:
                        "<div class='space-y-2 text-balance rounded-md bg-slate-100 p-3 text-xs'>   <p class='font-medium'>SSH public key authentication</p>   <p class='text-slate-500'> Download public key here and add it to your ~/.ssh/authorized_keys You'll need to create a user named retool. Click here for docs on how to use this feature.</p> </div>",
                },
            ],
            radio2: [],
            radio3: [],
        },
    },
    {
        name: "checkboxInputConditional",
        value: "",
        type: "checkbox",
        label: "Checkbox",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        required: false,
        disabled: false,
        checked: false,
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        isConditional: true,
        conditions: {
            true: [
                {
                    name: "textInput",
                    value: "",
                    type: "text",
                    label: "Name",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "emailInput",
                    value: "",
                    type: "email",
                    label: "Email Address",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "numberInput",
                    value: "",
                    type: "number",
                    label: "Number",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "passwordInput",
                    value: "",
                    type: "password",
                    label: "Password",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "urlInput",
                    value: "",
                    type: "url",
                    label: "Url",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "textareaInput",
                    value: "",
                    type: "textarea",
                    label: "Textarea",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "fileInput",
                    value: "",
                    type: "file",
                    label: "File",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "File",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "radioInput",
                    value: "",
                    type: "radio",
                    label: "Radio",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    checked: false,
                    options: [
                        {
                            label: "Radio 1",
                            subLabel: "",
                            value: "radio1",
                        },
                        {
                            label: "Radio 2",
                            subLabel: "",
                            value: "radio2",
                        },
                        {
                            label: "Radio 3",
                            subLabel: "",
                            value: "radio3",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "checkboxInput",
                    value: "",
                    type: "checkbox",
                    label: "Checkbox",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: false,
                    disabled: false,
                    checked: false,
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "selectInput",
                    value: "",
                    type: "select",
                    label: "Select",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    options: [
                        {
                            label: "Select Option 1",
                            value: "selectOption1",
                        },
                        {
                            label: "Select Option 2",
                            value: "selectOption2",
                        },
                        {
                            label: "Select Option 3",
                            value: "selectOption3",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "listInputWith1Option",
                    value: "",
                    type: "list",
                    label: "List with 1 Option",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    options: [
                        {
                            name: "file",
                            value: "",
                            type: "file",
                            label: "File",
                            subLabel: "",
                            placeholder: "File",
                            required: true,
                            disabled: false,
                            validation: {},
                            tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "listInputWith2Option",
                    value: "",
                    type: "list",
                    label: "List with 2 Options",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    options: [
                        {
                            name: "username",
                            value: "",
                            type: "text",
                            label: "Username",
                            subLabel: "",
                            placeholder: "UserName",
                            required: true,
                            disabled: false,
                            validation: {},
                            tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                        },
                        {
                            name: "password",
                            value: "",
                            type: "password",
                            label: "Password",
                            subLabel: "",
                            placeholder: "Password",
                            required: true,
                            disabled: false,
                            validation: {},
                            tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    type: "html",
                    content:
                        "<div class='space-y-2 text-balance rounded-md bg-slate-100 p-3 text-xs'>   <p class='font-medium'>SSH public key authentication</p>   <p class='text-slate-500'> Download public key here and add it to your ~/.ssh/authorized_keys You'll need to create a user named retool. Click here for docs on how to use this feature.</p> </div>",
                },
            ],
            false: [],
        },
    },
    {
        name: "selectInputConditional",
        value: "",
        type: "select",
        label: "Select",
        subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        required: true,
        disabled: false,
        options: [
            {
                label: "Select Option 1",
                value: "selectOption1",
            },
            {
                label: "Select Option 2",
                value: "selectOption2",
            },
            {
                label: "Select Option 3",
                value: "selectOption3",
            },
        ],
        validation: {},
        tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
        isConditional: true,
        conditions: {
            selectOption1: [
                {
                    name: "textInput",
                    value: "",
                    type: "text",
                    label: "Name",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "emailInput",
                    value: "",
                    type: "email",
                    label: "Email Address",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "numberInput",
                    value: "",
                    type: "number",
                    label: "Number",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "passwordInput",
                    value: "",
                    type: "password",
                    label: "Password",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
            ],
            selectOption2: [
                {
                    name: "urlInput",
                    value: "",
                    type: "url",
                    label: "Url",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "textareaInput",
                    value: "",
                    type: "textarea",
                    label: "Textarea",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "i.e. Users DB (readonly) or Internal Admin API",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "fileInput",
                    value: "",
                    type: "file",
                    label: "File",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    placeholder: "File",
                    required: true,
                    disabled: false,
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "radioInput",
                    value: "",
                    type: "radio",
                    label: "Radio",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    checked: false,
                    options: [
                        {
                            label: "Radio 1",
                            subLabel: "",
                            value: "radio1",
                        },
                        {
                            label: "Radio 2",
                            subLabel: "",
                            value: "radio2",
                        },
                        {
                            label: "Radio 3",
                            subLabel: "",
                            value: "radio3",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "checkboxInput",
                    value: "",
                    type: "checkbox",
                    label: "Checkbox",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: false,
                    disabled: false,
                    checked: false,
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "selectInput",
                    value: "",
                    type: "select",
                    label: "Select",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    options: [
                        {
                            label: "Select Option 1",
                            value: "selectOption1",
                        },
                        {
                            label: "Select Option 2",
                            value: "selectOption2",
                        },
                        {
                            label: "Select Option 3",
                            value: "selectOption3",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
            ],
            selectOption3: [
                {
                    name: "listInputWith1Option",
                    value: "",
                    type: "list",
                    label: "List with 1 Option",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    options: [
                        {
                            name: "file",
                            value: "",
                            type: "file",
                            label: "File",
                            subLabel: "",
                            placeholder: "File",
                            required: true,
                            disabled: false,
                            validation: {},
                            tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    name: "listInputWith2Option",
                    value: "",
                    type: "list",
                    label: "List with 2 Options",
                    subLabel: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                    required: true,
                    disabled: false,
                    options: [
                        {
                            name: "username",
                            value: "",
                            type: "text",
                            label: "Username",
                            subLabel: "",
                            placeholder: "UserName",
                            required: true,
                            disabled: false,
                            validation: {},
                            tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                        },
                        {
                            name: "password",
                            value: "",
                            type: "password",
                            label: "Password",
                            subLabel: "",
                            placeholder: "Password",
                            required: true,
                            disabled: false,
                            validation: {},
                            tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                        },
                    ],
                    validation: {},
                    tooltip: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, asperiores laboriosam. Veritatis laborum in sint",
                },
                {
                    type: "html",
                    content:
                        "<div class='space-y-2 text-balance rounded-md bg-slate-100 p-3 text-xs'>   <p class='font-medium'>SSH public key authentication</p>   <p class='text-slate-500'> Download public key here and add it to your ~/.ssh/authorized_keys You'll need to create a user named retool. Click here for docs on how to use this feature.</p> </div>",
                },
            ],
        },
    },
   
];
